// src/codex/config-gen.test.ts
import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateCodexConfig, writeCodexConfig } from "./config-gen";

test("generates valid TOML with dangerFullAccess and on-request", () => {
	const toml = generateCodexConfig({
		model: "o3",
		approvalPolicy: "on-request",
	});
	expect(toml).toContain('model = "o3"');
	expect(toml).toContain('sandbox_mode = "danger-full-access"');
	expect(toml).toContain('approval_policy = "on-request"');
});

test("generates TOML with different approval policy", () => {
	const toml = generateCodexConfig({
		model: "codex-mini-latest",
		approvalPolicy: "unless-allowed",
	});
	expect(toml).toContain('model = "codex-mini-latest"');
	expect(toml).toContain('approval_policy = "unless-allowed"');
});

test("generated TOML contains auto-generated header", () => {
	const toml = generateCodexConfig({
		model: "o3",
		approvalPolicy: "on-request",
	});
	expect(toml).toContain("Auto-generated by overstory");
});

describe("writeCodexConfig", () => {
	const tempDirs: string[] = [];

	afterEach(async () => {
		for (const dir of tempDirs) {
			await rm(dir, { recursive: true, force: true });
		}
		tempDirs.length = 0;
	});

	async function makeTempDir(): Promise<string> {
		const dir = await mkdtemp(join(tmpdir(), "config-gen-test-"));
		tempDirs.push(dir);
		return dir;
	}

	test("creates .codex directory and writes config.toml", async () => {
		const dir = await makeTempDir();
		await writeCodexConfig(dir, { model: "o3", approvalPolicy: "on-request" });

		const configPath = join(dir, ".codex", "config.toml");
		const content = await readFile(configPath, "utf-8");

		expect(content).toContain('model = "o3"');
		expect(content).toContain('approval_policy = "on-request"');
		expect(content).toContain('sandbox_mode = "danger-full-access"');
	});

	test("creates nested directory structure if needed", async () => {
		const dir = await makeTempDir();
		const nested = join(dir, "deep", "nested");

		await writeCodexConfig(nested, { model: "o3", approvalPolicy: "on-request" });

		const configPath = join(nested, ".codex", "config.toml");
		const content = await readFile(configPath, "utf-8");
		expect(content).toContain('model = "o3"');
	});

	test("overwrites existing config.toml", async () => {
		const dir = await makeTempDir();

		await writeCodexConfig(dir, { model: "o3", approvalPolicy: "on-request" });
		await writeCodexConfig(dir, { model: "gpt-4.1", approvalPolicy: "never" });

		const configPath = join(dir, ".codex", "config.toml");
		const content = await readFile(configPath, "utf-8");
		expect(content).toContain('model = "gpt-4.1"');
		expect(content).not.toContain('model = "o3"');
	});

	test("custom sandboxMode is written", async () => {
		const dir = await makeTempDir();

		await writeCodexConfig(dir, {
			model: "o3",
			approvalPolicy: "never",
			sandboxMode: "read-only",
		});

		const configPath = join(dir, ".codex", "config.toml");
		const content = await readFile(configPath, "utf-8");
		expect(content).toContain('sandbox_mode = "read-only"');
	});
});
