// src/codex/config-gen.ts

import { mkdir } from "node:fs/promises";
import { join } from "node:path";

interface CodexConfigOptions {
	model: string;
	approvalPolicy: "on-request" | "unless-allowed" | "never";
}

/** Generate .codex/config.toml content */
export function generateCodexConfig(opts: CodexConfigOptions): string {
	return `# Auto-generated by overstory. Do not edit.
model = "${opts.model}"
sandbox_policy = "dangerFullAccess"
approval_policy = "${opts.approvalPolicy}"
`;
}

/** Write .codex/config.toml to a worktree */
export async function writeCodexConfig(
	worktreePath: string,
	opts: CodexConfigOptions,
): Promise<void> {
	const dir = join(worktreePath, ".codex");
	await mkdir(dir, { recursive: true });
	await Bun.write(join(dir, "config.toml"), generateCodexConfig(opts));
}
