// src/codex/config-gen.test.ts
import { describe, test, expect } from "bun:test";
import { generateCodexConfig } from "./config-gen";

test("generates valid TOML with dangerFullAccess and on-request", () => {
	const toml = generateCodexConfig({
		model: "o3",
		approvalPolicy: "on-request",
	});
	expect(toml).toContain('model = "o3"');
	expect(toml).toContain('sandbox_policy = "dangerFullAccess"');
	expect(toml).toContain('approval_policy = "on-request"');
});

test("generates TOML with different approval policy", () => {
	const toml = generateCodexConfig({
		model: "codex-mini-latest",
		approvalPolicy: "unless-allowed",
	});
	expect(toml).toContain('model = "codex-mini-latest"');
	expect(toml).toContain('approval_policy = "unless-allowed"');
});

test("generated TOML contains auto-generated header", () => {
	const toml = generateCodexConfig({
		model: "o3",
		approvalPolicy: "on-request",
	});
	expect(toml).toContain("Auto-generated by overstory");
});
