// src/codex/config-gen.ts

import { mkdir } from "node:fs/promises";
import { join } from "node:path";

interface CodexConfigOptions {
	model: string;
	approvalPolicy: "on-request" | "unless-allowed" | "never";
	/** Sandbox mode for Codex execution. Defaults to "danger-full-access". */
	sandboxMode?: "danger-full-access" | "read-only" | "workspace-write";
}

/** Generate .codex/config.toml content */
export function generateCodexConfig(opts: CodexConfigOptions): string {
	const sandboxMode = opts.sandboxMode ?? "danger-full-access";
	return `# Auto-generated by overstory. Do not edit.
model = "${opts.model}"
sandbox_mode = "${sandboxMode}"
approval_policy = "${opts.approvalPolicy}"
`;
}

/** Write .codex/config.toml to a worktree */
export async function writeCodexConfig(
	worktreePath: string,
	opts: CodexConfigOptions,
): Promise<void> {
	const dir = join(worktreePath, ".codex");
	await mkdir(dir, { recursive: true });
	await Bun.write(join(dir, "config.toml"), generateCodexConfig(opts));
}
